name: transition-points
channels:
  - conda-forge
dependencies:
  - python[version='>=3.10']
  - numpy
  - gdal
  - conda
  - pyproj==3.7.0
  - matplotlib
  - scipy
  - fiona
  - nodejs
  - ipympl
  - geopandas
  - h5py
  - pandas
  - proj
  - rasterio
  - netcdf4
  - python-docx
  - libkml
  - simplekml
  - bash
  - notebook
  - ipywidgets[version='>=7.6']
  - jupyterlab[version='>=3']
  - ca-certificates
  - certifi
  - openssl
  - shapely
  - fastkml
  - tqdm
variables:
  PIP_USE_PEP517: '1'

